### ISSUE TITLE
Update breaks existing backpacks

### ISSUE THREAD

**Issue by tacotexmex** [taikedz/everamzah-backpacks#2]
[This commit](https://github.com/taikedz/everamzah-backpacks/commit/479357ed077720c21cf970639d7d6fd38165d49a) broke already existing backpack, rendering them as an unknown item.

**Comment by taikedz** [comment]
I expect [latest update][1] fixed it, please try

[1]: https://github.com/taikedz/everamzah-backpacks/commit/05cdbec45cb085a44068130ee30ca19ceab321ec

**Comment by tacotexmex** [comment]
Thanks, I'll try it! 🙂

**Comment by taikedz** [comment]
Seems to be fixed, closing.
